# Generated by Django 4.2.7 on 2025-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
